---
title: "hw1_cq2207"
author: "Carolina Q Cardoso"
date: "9/18/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r question 1}
library(tidyverse)

#QUESTION 1#

set.seed(1)

hw1_cq = tibble(
  norm_samp = rnorm(8),
  vec_logical = norm_samp > 0,
  vec_char = c("Mary","Jack","Jill","Jai","John","Jeff","Joe","Jose"),
  vec_factor = factor(c("EPI","BIOSTATS","BIOSTATS","POPFAM","EPI","EPI","POPFAM","EPI"))
)

#TAKE THE MEAN OF EACH VARIABLE#

mean(pull(hw1_cq,norm_samp))

mean(pull(hw1_cq,vec_logical))

mean(pull(hw1_cq,vec_char))

mean(pull(hw1_cq,vec_factor))

#WE CAN ONLY TAKE THE MEAN OF NUMERICAL AND LOGICAL ARGUMENTS. WHEN TRYING TO TAKE THE MEAN FOR THE CHARACTER AND FACTOR ARGUMENTS IT WAS NOT POSSIBLE.#

```
```{r question 1.2, eval = FALSE}

#CONVERT LOGICAL, FACTOR AND CHARACTER VECTORS TO NUMERIC#

as.numeric(pull(hw1_cq,vec_logical))

as.numeric(pull(hw1_cq,vec_char))

as.numeric(pull(hw1_cq,vec_factor))

#LOGICAL AND FACTOR VECTORS WERE ABLE TO CONVERT DATA TO NUMERIC, BUT CHARACTER VECTOR INTRODUCES A VECTOR OF NA VALUES OF THE SAME LENGHT, THAT IS, IT IS NOT ABLE TO PROPERLY CONVERT THE CHARACTER VECTOR TO NUMERIC. IT HELPS TO UNDERSTAND WHY YOU CANNOT TAKE THE MEAN OF THE CHARACTER VECTOR: BECAUSE IT IS NOT ABLE TO READ THE VECTOR VALUES AS NUMERIC VALUES IN ORDER TO TAKE THE MEAN#

```
```{r question 1.3, eval = FALSE}

#CONVERT LOGICAL VECTOR TO NUMERIC AND MULTIPLY SAMPLE BY RESULT#

as.numeric(pull(hw1_cq,vec_logical))*(pull(hw1_cq,norm_samp))

#CONVERT LOGICAL VECTOR TO FACTOR AND MULTIPLY SAMPLE BY RESULT#

as.factor(pull(hw1_cq,vec_logical))*(pull(hw1_cq,norm_samp))

#CONVERT LOGICAL VECTOR TO FACTOR AND THAT RESULT TO NUMERIC THEN MULTIPLYING THE SAMPLE BY THE FINAL RESULT#

as.factor(pull(hw1_cq,vec_logical))
as.numeric(pull(hw1_cq,vec_logical))*(pull(hw1_cq,norm_samp))

``` 
```{r question 2}

#Question 2#

set.seed(29)

hw1_cq2 = tibble(
  x = rnorm(500),
  y = rnorm(500),
  vec_logic = x + y > 1,
  vec_numeric = as.numeric(vec_logic),
  vec_fact = as.factor(vec_logic),
)

```

the dataframe `hw1_cq2` has `r nrow(hw1_cq2)` rows and `r ncol(hw1_cq2)` columns
the mean of x is `r mean(pull(hw1_cq2,x))`,
the median is `r median(pull(hw1_cq2,x))`, and the standard deviation is `r sd(pull(hw1_cq2,x))`
the proportion of cases for which x + y > 1 is `r mean(pull(hw1_cq2, vec_logic))` 

```{r yx_scatter}
p1 <- ggplot(hw1_cq2, aes(x = x, y = y, color= vec_logic)) + geom_point()

ggplot(hw1_cq2, aes(x = x, y = y, color= vec_numeric)) + geom_point()

ggplot(hw1_cq2, aes(x = x, y = y, color= vec_fact)) + geom_point()

#R USED THE SAME COLOR SCHEME FOR BOTH PLOTS THAT HAD "TRUE/FALSE" AND ONLY ASSIGNED ONE COLOR FOR EACH VALUE, WHILE FOR VEC_NUMERIC WAS ASSIGNED A COLOR GRADIENT FROM VALUE 0 TO 1 INSTEAD OF JUST TWO DIFFERENT COLORS

ggsave("hw1_cq2.pdf", plot = p1)

```
